Repository qiniu/python-sdk, pull requests merged in 2020-08, with the labels that each got.

#371 Develop
  .travis.yml
  qiniu/http.py
  qiniu/region.py
  qiniu/services/storage/bucket.py
  qiniu/services/storage/uploader.py
  setup.py
  test_qiniu.py
Labels: size/L

#373 Develop
  CHANGELOG.md
  examples/get_domaininfo.py
  qiniu/__init__.py
  qiniu/http.py
  qiniu/services/cdn/manager.py
  qiniu/services/storage/bucket.py
  qiniu/services/storage/uploader.py
  test_qiniu.py
Labels: size/M

#375 add test
  CHANGELOG.md
  test_qiniu.py
Labels: size/M

#376 Develop
  qiniu/auth.py
Labels: size/XS

#377 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS
